### ISSUE TITLE
SQLServer varchar(max) is converted as "com.intellij.database.remote.jdbc.LobInfo$ClobInfo@..."

### ISSUE THREAD

**Issue by rakk** [kTT/dbunit-extractor#12]
Environment:
* IntelliJ: 2017.2.3
* DbUnit Extractor: 1.2
* SQL: SQLServer, jtds driver

For column varchar(max) and value like 
`format:format(/deliveryPlaceholderParams/previousBusinessDate, '%1$tY%1$tm%1$td')`
instead of value we get: `com.intellij.database.remote.jdbc.LobInfo$ClobInfo@...`
(value is visible in datagrid output)

Please check also exporting in xml file. Not working on my machine but this might be local issue.

**Comment by kTT** [comment]
Fixed in 1.3 

For exporting in xml check https://github.com/kTT/dbunit-extractor#known-issues you are missing "useCursors=true" parameter in your connection url.
