### ISSUE TITLE
NoSuchMethodError: com.intellij.database.datagrid.DataGrid.getDataModel()

### ISSUE THREAD

**Issue by srenkens** [kTT/dbunit-extractor#4]
Hey kTT,

Would love to use the plugin but unfortunately i'm getting this error when trying to copy one or more rows:

10:32:46 NoSuchMethodError: com.intellij.database.datagrid.DataGrid.getDataModel()Lcom/intellij/database/datagrid/DataGridModel;

**Comment by kTT** [comment]
Hey @srenkens ,

Which version of intellij do you use?

**Comment by srenkens** [comment]
I'am using IntelliJ IDEA 15.0.1.

**Comment by kTT** [comment]
@srenkens It seems that plugin doesn't work on Intellij 15. I will fix it as soon as possible.
Thank you for reporting this issue.

**Comment by kTT** [comment]
Fixed in version 0.6 (commit 375f09dbfb04b7ea0c8fcd736875c872d22176d3) and it's ready for update in Intellij. :)
