### ISSUE TITLE
Plugin installs but does not appear (IntelliJ 13.06)

### ISSUE THREAD

**Issue by thorbolo** [kTT/dbunit-extractor#5]
Hi! I would love to use this Plugin, but:
I can install the plugin and it appears as installed in the plugin manager.

But I can not find any preferences (like in the promo video) and the "copy to clipboard as dbunit-xml" does not appear in the contextmenu.

Maybe there is a problem with the plugin and Intellij 13, since your project is pretty young :)

**Comment by kTT** [comment]
Sorry but I don't support Intellij 13, there is a mistake in compatible build version. The good news is that this project is open source and you can make it working on Intellij 13, it'll be great. :)
